# Generated by Django 3.1.6 on 2021-06-20 08:51

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210607_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/images/placeholder.png', null=True, upload_to=accounts.models.upload_to),
        ),
    ]
