// export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
// export const LOGIN_FAIL = 'LOGIN_FAIL';
// export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
// export const SIGNUP_FAIL = 'SIGNUP_FAIL';
// // export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
// // export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
// // export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
// // export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
// // export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
// // export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
// // export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
// // export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
// // export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
// // export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
// // export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
// // export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';
// // export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS';
// // export const FACEBOOK_AUTH_FAIL = 'FACEBOOK_AUTH_FAIL';
// export const LOGOUT = 'LOGOUT';


export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

// Profile Dispatch States
export const LOAD_USER_PROFILE_SUCCESS = 'LOAD_USER_PROFILE_SUCCESS';
export const LOAD_USER_PROFILE_FAIL = 'LOAD_USER_PROFILE_FAIL';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL';